kind: pipeline
name: default
type: docker

steps:
- name: debug print variables
  image: alpine
  commands:
  - echo "host $swarm_host"
  - echo "docker_cert $docker_cert"
  - echo "docker_key $docker_key"
  - echo "docker_cacert $docker_cacert"
  environment:
    swarm_host:
      from_secret: swarm_host
    docker_cert:
      from_secret: swarm_cert
    docker_key:
      from_secret: swarm_key
    docker_cacert:
      from_secret: swarm_cacert

- name: deploy
  image: codestation/drone-stack
  settings:
    host:
      from_secret: swarm_host
    stack_name: diun-swarm
    compose: diun-swarm.yml
    tlsverify: true
    docker_cert:
      from_secret: swarm_cert
    docker_key:
      from_secret: swarm_key
    docker_cacert:
      from_secret: swarm_cacert

trigger:
  branch:
  - master