kind: pipeline
type: docker
name: default

steps:
  - name: clone environment variables repo
    image: alpine/git
    environment:
      CLONE_PATH: swarm-envs
    commands:
      - git clone https://github.com/jon-chen-configs/swarm-env-config.git $CLONE_PATH

  # - name: debug
  #   image: alpine
  #   commands:
  #     - pwd
  #     - whoami
  #     - touch ./test
  #     - ls -la /
  #     - ls -la /drone/src
  #     - ls -la ./

  - name: inject environment variables into compose file
    image: tiangolo/docker-with-compose
    environment:
      COMPOSE_ENV: swarm-envs/swarm.env
      COMPOSE_FILE: diun-swarm.yml
    commands:
      - docker-compose --env-file $COMPOSE_ENV --file $COMPOSE_FILE config > .compose.yml

  - name: deploy
    image: automagistre/docker:stable
    environment:
      STACK_NAME: diun-swarm-test
      COMPOSE_FILE: diun-swarm.yml
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    commands:
      - docker stack deploy --prune --with-registry-auth --compose-file .compose.yml $STACK_NAME

volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock

trigger:
  event: [push, custom]
  branch: [master]
  repo:
    include:
      - jon-chen-configs/swarm-env-config
      - jon-chen-configs/diun-stack