version: "3.7"
services:
  diun:
    image: crazymax/diun:latest
    command: serve
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        # Docker (20.10.3) on Synology bug where env vars from env_file 
        # not set on container.
        # constraints: [node.platform.arch != aarch64]
        constraints:
          - node.platform.arch != aarch64
          - node.hostname != ${NAS_HOSTNAME}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "diun_data:/data"
    env_file: ["${ENV_DIR:-swarm-envs}/swarm/diun-stack/diun.env"]
    environment:
      # - "PUID=${NET_PUID}"
      # - "PGID=${NET_PGID}"
      - "TZ=${TZ}"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 0 * * *"
      - "DIUN_PROVIDERS_SWARM=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"

volumes:
  diun_data:
    driver_opts:
      type: nfs
      o: addr=${NAS_HOST},nolock,noresvport,vers=2
      device: :${DATADIR}/docker-stack/diun
